In [ ]:
import numpy as np
a = np.array([1, 2, 3])
print(a)

In [ ]:
b = np.array([[1, 2], [3, 4]])
print(b)

In [ ]:
c = np.zeros((2, 3))
print(c)

In [ ]:
d = np.ones((3, 3))
print(d)

In [ ]:
e = np.full((2, 2), 7)
print(e)

In [ ]:
f = np.eye(4)
print(f)

In [ ]:
g = np.random.rand(2, 3)
print(g)

In [ ]:
h = np.random.randint(0, 10, (3, 3))
print(h)

In [ ]:
i = np.arange(0, 10, 2)
print(i)

In [ ]:
j = np.linspace(0, 1, 5)
print(j)

In [ ]:
print(a.shape)

In [ ]:
print(b.ndim)

In [ ]:
print(c.size)

In [ ]:
print(d.dtype)

In [ ]:
reshaped = np.reshape(h, (1, 9))
print(reshaped)

In [ ]:
print(h.flatten())

In [ ]:
print(h.flatten())

In [ ]:
float_arr = a.astype(float)
print(float_arr)

In [ ]:
print(a.nbytes)

In [ ]:
view = h.view()
print(view)

In [ ]:
print(a[1])

In [ ]:
print(a[1:3])

In [ ]:
print(b[0:2, 1])

In [ ]:
print(a[a > 1])

In [ ]:
print(a[[0, 2]])

In [ ]:
a[0] = 10
print(a)

In [ ]:
a[a > 5] = 0
print(a)

In [ ]:
print(b[1])

In [ ]:
print(b[:, 0])

In [ ]:
print(np.arange(10)[::2])

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
print(x + y)

In [ ]:
print(x - y)

In [ ]:
print(x * y)

In [ ]:
print(y / x)

In [ ]:
print(x ** 2)

In [ ]:
print(np.dot(x, y))

In [ ]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[2, 0], [1, 2]])
print(np.matmul(mat1, mat2))

In [ ]:
print(np.sum(mat1))

In [ ]:
print(np.mean(x))

In [ ]:
print(np.std(x))

In [ ]:
arr = np.array([1, 2, 3])

In [ ]:
print(arr + 5)

In [ ]:
print(arr * 3)

In [ ]:
mat = np.array([[1, 2, 3], [4, 5, 6]])
print(mat + arr)

In [ ]:
print(np.sqrt(arr))

In [ ]:
print(np.exp(arr))

In [ ]:
print(np.log(arr + 1))  

In [ ]:
print(np.sin(arr))

In [ ]:
print(np.cos(arr))

In [ ]:
print(np.abs([-1, -2, 3]))

In [ ]:
print(np.round([1.4, 2.6, 3.1]))

In [ ]:
print(np.min(mat))

In [ ]:
print(np.max(mat))

In [ ]:
print(np.argmin(mat))

In [ ]:
print(np.argmax(mat))

In [ ]:
print(np.sum(mat, axis=0))

In [ ]:
print(np.sum(mat, axis=0))

In [ ]:
print(np.mean(mat, axis=1))

In [ ]:
print(np.cumsum(arr))

In [ ]:
print(np.cumprod(arr))

In [ ]:
print(np.median(mat))

In [ ]:
square = np.array([[1, 2], [3, 4]])
print(np.linalg.det(square))

In [ ]:
print(np.linalg.inv(square))

In [ ]:
print(np.linalg.matrix_rank(square))

In [ ]:
eig_vals, eig_vecs = np.linalg.eig(square)
print(eig_vals)

In [ ]:
print(eig_vecs)

In [ ]:
A = np.array([[3, 1], [1, 2]])
b = np.array([9, 8])
x = np.linalg.solve(A, b)
print(x)

In [ ]:
v = np.array([3, 4])
print(np.linalg.norm(v))

In [ ]:
print(np.trace(square))

In [ ]:
q, r = np.linalg.qr(square)
print(q)

In [ ]:
u, s, vh = np.linalg.svd(square)
print(s)

In [ ]:
print(np.any(arr > 2))

In [ ]:
print(np.all(arr > 0))

In [ ]:
x = np.array([True, False, True])
y = np.array([False, False, True])
print(np.logical_and(x, y))

In [ ]:
print(np.logical_or(x, y))

In [ ]:
print(np.logical_not(x))

In [ ]:
z = np.array([1, 2, 3])
print(np.where(z > 1, 'yes', 'no'))

In [ ]:
print(np.count_nonzero([0, 1, 2, 0]))

In [ ]:
a = np.array([1, 1, 2, 3, 3])
print(np.unique(a))

In [ ]:
print(np.array_equal([1, 2], [1, 2]))

In [ ]:
print(np.greater([1, 3, 5], [2, 3, 1]))

In [ ]:
a = np.array([3, 1, 2])
print(np.sort(a))

In [ ]:
b = np.array([[3, 1], [2, 4]])
print(np.sort(b, axis=1))

In [ ]:
print(np.argsort(a))

In [ ]:
c = np.array([1, 3, 5])
print(np.searchsorted(c, 4))

In [ ]:
print(np.partition(a, 1))

In [ ]:
print(np.argmax(b, axis=0))

In [ ]:
print(np.argmin(b, axis=1))

In [ ]:
arr = np.array([1, 5, 10])
print(np.clip(arr, 2, 8))

In [ ]:
print(np.argsort([4, 1, 3]))

In [ ]:
x = np.array([1, 2, 3, 4])
print(np.where(x > 2))

In [ ]:
np.save('array.npy', x)
loaded = np.load('array.npy')
print(loaded)

In [ ]:
np.savez('arrays.npz', a=x, b=arr)
data = np.load('arrays.npz')
print(data['a'], data['b'])

In [ ]:
np.savetxt('array.txt', x)
x2 = np.loadtxt('array.txt')
print(x2)

In [ ]:
np.savetxt('custom.txt', x, delimiter=',')
x3 = np.loadtxt('custom.txt', delimiter=',')
print(x3)

In [ ]:
np.savetxt('ints.csv', np.array([[1,2],[3,4]]), fmt='%d', delimiter=',')
ints = np.loadtxt('ints.csv', delimiter=',')
print(ints)

In [ ]:
arr = np.arange(6)
print(arr.reshape(2, 3))

In [ ]:
print(np.expand_dims(arr, axis=0))

In [ ]:
a = np.array([[[1, 2, 3]]])
print(np.squeeze(a))

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.vstack((a, b)))

In [ ]:
print(np.hstack((a, b)))

In [ ]:
print(np.dstack((a, b)))

In [ ]:
print(np.concatenate(([a], [b]), axis=0))

In [ ]:
c = np.array([1, 2, 3, 4])
print(np.split(c, 2))

In [ ]:
d = np.array([[1, 2], [3, 4]])
print(np.vsplit(d, 2))

In [ ]:
print(np.hsplit(d, 2))

In [ ]:
print(np.random.randint(0, 100, 5))

In [ ]:
print(np.random.random(5))

In [ ]:
print(np.random.normal(0, 1, 5))

In [ ]:
print(np.random.choice([10, 20, 30]))

In [ ]:
arr = np.array([1, 2, 3, 4])
np.random.shuffle(arr)
print(arr)

In [ ]:
print(np.random.permutation([1, 2, 3, 4]))

In [ ]:
np.random.seed(42)
print(np.random.rand())

In [ ]:
print(np.random.rand(2, 3))

In [ ]:
print(np.random.uniform(low=0, high=10, size=5))

In [ ]:
print(np.random.binomial(n=10, p=0.5, size=5))

In [ ]:
a = np.array([1.8, 2.5, 3.1])
print(np.floor(a))

In [ ]:
print(np.ceil(a))

In [ ]:
print(np.trunc(a))

In [ ]:
x = np.array([10, 20, 30])
y = np.array([3, 7, 9])
print(np.mod(x, y))

In [ ]:
print(np.remainder(x, y))

In [ ]:
print(np.gcd(12, 18))

In [ ]:
print(np.lcm(6, 8))

In [ ]:
print(np.power(2, 3))

In [ ]:
print(np.sign([-10, 0, 10]))

In [ ]:
print(np.reciprocal([1, 2, 0.5]))

In [ ]:
arr = np.array([1, np.nan, 3])
print(np.isnan(arr))

In [ ]:
arr2 = np.array([1, np.inf, -np.inf])
print(np.isinf(arr2))

In [ ]:
arr[np.isnan(arr)] = 0
print(arr)

In [ ]:
arr2[np.isinf(arr2)] = 9999
print(arr2)

In [ ]:
arr3 = np.array([1, 2, np.nan])
print(np.nansum(arr3))

In [ ]:
print(np.nanmean(arr3))

In [ ]:
print(np.nanmax(arr3))

In [ ]:
print(np.nanmin(arr3))

In [ ]:
m = np.array([[1, np.nan], [3, 4]])
col_means = np.nanmean(m, axis=0)
inds = np.where(np.isnan(m))
m[inds] = np.take(col_means, inds[1])
print(m)

In [ ]:
arr = np.array([1, np.nan, 2, np.nan])
print(np.isnan(arr).sum())

In [ ]:
print(np.bitwise_and(5, 3)) 

In [ ]:
print(np.bitwise_or(5, 3))

In [ ]:
print(np.bitwise_xor(5, 3))

In [ ]:
print(np.left_shift(1, 2))

In [ ]:
print(np.right_shift(4, 1))

In [ ]:
print(np.binary_repr(10, width=8))

In [ ]:
x = np.array([True, False])
y = np.array([False, True])
print(np.logical_xor(x, y))

In [ ]:
bools = np.array([True, False])
print(bools.astype(int))

In [ ]:
ints = np.array([0, 1, 2])
print(ints.astype(bool))

In [ ]:
a = np.array([[1, 2], [3, 4]])
print(a.T)

In [ ]:
print(np.dot(a, a))

In [ ]:
print(np.linalg.matrix_power(a, 2))

In [ ]:
print(np.identity(3))

In [ ]:
print(np.diag(a))

In [ ]:
d = np.array([1, 2, 3])
print(np.diag(d))

In [ ]:
print(np.triu(a))

In [ ]:
print(np.tril(a))

In [ ]:
b = np.zeros((3, 3))
np.fill_diagonal(b, 1)
print(b)

In [ ]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(np.diag(c, k=1))

In [ ]:
a = np.array([1, 2, 3, 4])
print(np.fft.fft(a))

In [ ]:
f = np.fft.fft(a)
print(np.fft.ifft(f))

In [ ]:
print(np.fft.fftfreq(4))

In [ ]:
img = np.array([[1, 2], [3, 4]])
print(np.fft.fft2(img))

In [ ]:
f2 = np.fft.fft2(img)
print(np.fft.ifft2(f2))

In [ ]:
print(np.fft.fftshift(f2))

In [ ]:
print(np.fft.ifftshift(f2))

In [ ]:
f = np.fft.fft(a)
power = np.abs(f)**2
print(power)

In [ ]:
phase = np.angle(f)
print(phase)

In [ ]:
print(np.fft.rfft(a))

In [ ]:
a = np.array([1, 2, 2, 3])

In [ ]:
print(np.unique(a))

In [ ]:
b = np.array([2, 3, 4])
print(np.intersect1d(a, b))

In [ ]:
print(np.union1d(a, b))

In [ ]:
print(np.setdiff1d(a, b))

In [ ]:
print(np.setxor1d(a, b))

In [ ]:
unique, counts = np.unique(a, return_counts=True)
print(dict(zip(unique, counts)))

In [ ]:
print(set(a) == set(b))

In [ ]:
print(np.asarray(list(set(a))))

In [ ]:
arr2d = np.array([[1, 2], [1, 2], [3, 4]])
print(np.unique(arr2d, axis=0))

In [ ]:
data = np.random.randint(0, 10, 100)
hist, bins = np.histogram(data, bins=5)
print(hist)
print(bins)

In [ ]:
print(np.digitize([1, 2, 6], bins=[0, 3, 6]))

In [ ]:
print(np.histogram(data, bins=[0, 3, 6, 10]))
(array([30, 21, 49]), array([ 0,  3,  6, 10]))
hist, bins = np.histogram(data, bins=5, density=True)
print(hist)

In [ ]:
hist, bihist, bins = np.histogram(data, bins=5)
cumsum = np.cumsum(hist)

In [ ]:
print(cumsum)ns = np.histogram(data, bins=5)
cumsum = np.cumsum(hist)

In [ ]:
print(cumsum)hist, bins = np.histogram(data, bins=5)
cumsum = np.cumsum(hist)
print(cumsum)

In [ ]:
x = np.random.rand(100)
y = np.random.rand(100)
H, xedges, yedges = np.histogram2d(x, y, bins=5)
print(H)

In [ ]:
print(hist.flatten())

In [ ]:
values = np.array([0, 1, 1, 3, 4, 4, 4])
print(np.bincount(values))

In [ ]:
weights = np.ones_like(values)
print(np.bincount(values, weights=weights))

In [ ]:
bins = [0, 1, 2, 3, 4, 5]
print(np.digitize([0.5, 2.2, 3.9], bins))

In [ ]:
x = np.array([1, 2, 3])
y = np.array([4, 5])
X, Y = np.meshgrid(x, y)
print(X)
print(Y)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1, 1, 5), np.linspace(-1, 1, 5))
Z = X**2 + Y**2
print(Z)

In [ ]:
i, j = np.indices((2, 3))
print(i)
print(j)

In [ ]:
og = np.ogrid[0:3, 0:2]
print(og[0])
print(og[1])

In [ ]:
mg = np.mgrid[0:3, 0:2]
print(mg)

In [ ]:
x = np.linspace(0, 1, 3)
y = np.linspace(0, 1, 3)
z = np.linspace(0, 1, 3)
X, Y, Z = np.meshgrid(x, y, z)
print(X.shape)

In [ ]:
xi, yi = np.meshgrid([1, 2], [3, 4], indexing='ij')
print(xi)
print(yi)

In [ ]:
x = [1, 2]
y = [3, 4]
X, Y = np.meshgrid(x, y)
print(np.array([X.ravel(), Y.ravel()]).T)

In [ ]:
r = np.linspace(0, 1, 5)
theta = np.linspace(0, 2 * np.pi, 5)
R, T = np.meshgrid(r, theta)
print(R)
print(T)

In [ ]:
phi = np.linspace(0, np.pi, 3)
theta = np.linspace(0, 2 * np.pi, 4)
PHI, THETA = np.meshgrid(phi, theta)
print(PHI)
print(THETA)

In [ ]:
dt = np.dtype([('name', 'U10'), ('age', 'i4')])
people = np.array([('Alice', 25), ('Bob', 30)], dtype=dt)
print(people)

In [ ]:
print(people['name'])

In [ ]:
sorted_people = np.sort(people, order='age')
print(sorted_people)

In [ ]:
print(people[people['age'] > 25])

In [ ]:
print(people[people['age'] > 25])

In [ ]:
new = np.array([('Charlie', 22)], dtype=dt)
people = np.concatenate((people, new))
print(people)

In [ ]:
dt_nested = np.dtype([('coords', [('x', 'f4'), ('y', 'f4')]), ('value', 'i4')])
data = np.array([((1.0, 2.0), 10)], dtype=dt_nested)
print(data)

In [ ]:
print(people[['name', 'age']])

In [ ]:
import numpy.ma as ma
data = ma.array([1, 2, 3], mask=[0, 1, 0])
print(data)

In [ ]:
print(data.mask)

In [ ]:
print(data.mean())

In [ ]:
print(data.filled(-1))

In [ ]:
masked = ma.masked_equal([1, -99, 3], -99)
print(masked)

In [ ]:
x = np.array([1, 2, 3, 4])
masked = ma.masked_where(x > 2, x)
print(masked)

In [ ]:
a = ma.masked_less([1, 2, 3], 2)
b = ma.masked_greater([1, 2, 3], 2)
combined = ma.mask_or(a.mask, b.mask)
print(combined)

In [ ]:
print(data.compressed())

In [ ]:
print(ma.std(masked))

In [ ]:
matrix = np.array([[1, 2], [3, 4]])
row = np.array([10, 20])
print(matrix + row)

In [ ]:
col = np.array([[1], [2]])
print(matrix - col)

In [ ]:
a = np.array([1, 2])
b = np.array([3, 4])
print(np.outer(a, b))

In [ ]:
arr = np.array([1, 2, 3])
print(arr[:, None] + arr)

In [ ]:
m = np.array([[1, 2], [3, 4]])
norms = np.linalg.norm(m, axis=1, keepdims=True)
print(m / norms)

In [ ]:
x = np.array([1, 2, 3])
y = 2
print(x == y)

In [ ]:
a = np.ones((3, 3))
b = np.array([1, 2, 3])
print(a * b[:, np.newaxis])

In [ ]:
dates = np.array(['2025-06-01', '2025-06-10'], dtype='datetime64[D]')
print(dates)

In [ ]:
print(np.arange('2025-01', '2025-04', dtype='datetime64[M]'))

In [ ]:
print(dates + np.timedelta64(5, 'D'))

In [ ]:
print(dates[1] - dates[0])

In [ ]:
9 days

In [ ]:
delta = np.array(['2025-06-10'], dtype='datetime64[D]') - np.array(['2025-06-01'], dtype='datetime64[D]')
print(delta.astype(int))

In [ ]:
print(np.datetime64('today', 'D'))
2025-06-29
print(np.arange('2025-01', '2026-01', dtype='datetime64[M]'))
['2025-01' '2025-02' '2025-03' '2025-04' '2025-05' '2025-06' '2025-07'
 '2025-08' '2025-09' '2025-10' '2025-11' '2025-12']
months = np.arange('2025-01', '2025-04', dtype='datetime64[M]')
print(np.diff(months))
[1 1]
x = np.arange(1000000)
print(x * 2)
[      0       2       4 ... 1999994 1999996 1999998]
arr = np.array([1, 2, 3])
print(np.where(arr > 2, 100, 0))
[  0   0 100]
arr = np.arange(10)
view = arr.view()
print(view.base is arr) 
True
a = np.array([1, 2, 3])
b = a.view()
b[0] = 100
print(a)
[100   2   3]
x = np.arange(1000000)
print(x[::100])
[     0    100    200 ... 999700 999800 999900]
x = np.array([1, 2, 3])
x *= 2
print(x)
[2 4 6]
x = np.array([1.0, 2.0, 3.0])
y = np.empty_like(x)
np.add(x, x, out=y)
print(y)
[2. 4. 6.]
a = np.array([1.00001, 1.00002])
b = np.array([1.00002, 1.00001])
print(np.allclose(a, b, atol=1e-4))